from datetime import datetime, timedelta
from jose import jwt, JWTError
import os

SECRET_KEY = os.getenv("SECRET_KEY", "super-secret-attendance-key")
ALGORITHM = "HS256"

def generate_secure_qr_session(course_id: str, duration_minutes: float = 5.0) -> str:
    """
    Generates a secure QR payload carrying a signed JWT encapsulating expiration logic.
    Instead of generating a PNG file here natively, we just return the string payload 
    so the Frontend React component can render it dynamically using Google API.
    """
    expiration_time = datetime.utcnow() + timedelta(minutes=duration_minutes)
    
    payload = {
        "course_id": course_id,
        "type": "qr_attendance",
        "exp": expiration_time
    }
    
    encoded_jwt = jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

def verify_qr_token(token: str) -> dict:
    """
    Decodes the JWT to ensure it exists, was generated by us cleanly, and hasn't expired.
    Raises JWTError if invalid or strictly expired.
    """
    payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
    if payload.get("type") != "qr_attendance":
        raise ValueError("Invalid token type")
    return payload
